{{- $fullName := .Values.appName | default "speech-ai" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
