{{- $fullName := .Values.appName | default "speech-ai" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-service
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
      protocol: TCP
      name: http-streamlit
  selector:
    app: {{ $fullName }}
